# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=255)),
                ('query', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='products_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellers_id', models.CharField(blank=True, max_length=255)),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('product_images', models.ImageField(upload_to='images/')),
                ('product_details', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='sellers_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('sellers_contact_address', models.CharField(blank=True, max_length=255)),
                ('sellers_contact_number', models.IntegerField(default=0)),
            ],
        ),
    ]
