# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_contact_model_products_model_sellers_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellers_model',
            name='sellers_contact_number',
            field=models.IntegerField(),
        ),
    ]
