# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-08 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_auto_20171007_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_model',
            name='product_details',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
