# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_contact_model_product_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_model',
            name='product_details',
        ),
        migrations.AlterField(
            model_name='products_model',
            name='product_images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
