# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_auto_20171012_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products_model',
            name='product_images',
            field=models.ImageField(default=0.0009419930589985126, upload_to='images/'),
            preserve_default=False,
        ),
    ]
